server {
    listen 80;
    
    # Change '_' to your EC2 domain or public IP later
    server_name _; 

    # 1. Serve the compiled Vite React Dashboard natively
    root /var/www/taskforge/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Reverse Proxy incoming API traffic securely to Node
    location /jobs {
        proxy_pass http://localhost:3001/jobs;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Transparently upgrade HTTP connections to keep Socket.io alive!
    location /socket.io/ {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
